server:
  port: 8002
spring:
  main:
    allow-bean-definition-overriding: true
  redis:
    host: 127.0.0.1 # Redis服务器地址
    database: 0 # Redis数据库索引（默认为0）
    port: 6379 # Redis服务器连接端口
    timeout: 1000ms # 连接超时时间
  cloud:
    nacos:
      server-addr: localhost:8848
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  application:
    #应用的名称，可选
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reggie?useUnicode=true&characterEncoding=utf8
    username: root
    password: Yy336699
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
