server:
  port: 8005
spring:
  cloud:
    nacos:
      server-addr: localhost:8848
  application:
    #应用的名称，可选
    name: category-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/reggie?useUnicode=true&characterEncoding=utf8
    username: root
    password: Yy336699
mybatis-plus:
  configuration:
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID
